// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbfkrhsxzwzudbhulery.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiZmtyaHN4end6dWRiaHVsZXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzcxMzgsImV4cCI6MjA1OTYxMzEzOH0.kZNaYV3O_DWcuJmuQq-0ucGWQgEYj9gAoKGQJ6zh-lI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);